# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 361, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.add_shop_text = QtWidgets.QLineEdit(self.centralwidget)
        self.add_shop_text.setGeometry(QtCore.QRect(380, 110, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.add_shop_text.setFont(font)
        self.add_shop_text.setObjectName("add_shop_text")
        self.shop_add = QtWidgets.QPushButton(self.centralwidget)
        self.shop_add.setGeometry(QtCore.QRect(370, 180, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.shop_add.setFont(font)
        self.shop_add.setObjectName("shop_add")
        self.delete_shop_text = QtWidgets.QLineEdit(self.centralwidget)
        self.delete_shop_text.setGeometry(QtCore.QRect(380, 320, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.delete_shop_text.setFont(font)
        self.delete_shop_text.setObjectName("delete_shop_text")
        self.shop_remove = QtWidgets.QPushButton(self.centralwidget)
        self.shop_remove.setGeometry(QtCore.QRect(380, 380, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.shop_remove.setFont(font)
        self.shop_remove.setObjectName("shop_remove")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 270, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SHOP NAMES"))
        self.label.setText(_translate("MainWindow", "ADD NEW SHOP or DELETE"))
        self.label_2.setText(_translate("MainWindow", "ADD SHOP"))
        self.shop_add.setText(_translate("MainWindow", "ADD SHOP"))
        self.shop_remove.setText(_translate("MainWindow", "REMOVE SHOP"))
        self.label_3.setText(_translate("MainWindow", "DELETE SHOP"))
